version: '3.8'

services:
  bazaar_stage_v3_rabbitmq:
    image: rabbitmq:3-management
    container_name: bazaar_stage_v3_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bazaar_stage_v3_redis:
    image: redis:latest
    container_name: bazaar_stage_v3_redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass ""

  bazaar_stage_v3_backend_1:
    build: .
    container_name: bazaar_stage_v3_backend_1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=bazaar_stage_v3_rabbitmq
      - SPRING_DATA_REDIS_HOST=bazaar_stage_v3_redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=
    depends_on:
      - bazaar_stage_v3_rabbitmq
      - bazaar_stage_v3_redis

  bazaar_stage_v3_backend_2:
    build: .
    container_name: bazaar_stage_v3_backend_2
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=bazaar_stage_v3_rabbitmq
      - SPRING_DATA_REDIS_HOST=bazaar_stage_v3_redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=
    depends_on:
      - bazaar_stage_v3_rabbitmq
      - bazaar_stage_v3_redis

  nginx:
    image: nginx:latest
    container_name: bazaar_stage_v3_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bazaar_stage_v3_backend_1
      - bazaar_stage_v3_backend_2
